### ISSUE TITLE
Problema para acceder con el realmlist del server

### ISSUE THREAD

**Issue by crixymln** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#1]
Presento problemas para entrar al alpha. Mi cuenta ya fue activada por soporte luego de que por medio de un sorteo, Darma gamer, me diera acceso al alpha.  Este es el error que me aparece. https://imgur.com/gallery/tG7oJ3a

**Comment by Zorodragneel24** [comment]
Hola, tuve el mismo problema, para que lo soluciones comunícate con Darma de nuevo y dile que te facilite el ejecutable ese archivo .exe lo vas a pegar en la carpeta donde tengas el juego y le das abrir al ejecutable y listo.

**Comment by crixymln** [comment]
Ya lo intenté y sigue el mismo problema. Ya no se que mas intentar. He bajado el wow de tauri y warmane y ambos me arrojan el mismo error. Alguna otra idea?

**Comment by Zorodragneel24** [comment]
Cuando copiaste en archivo .wtf te aseguraste de borrar todo el contenido? o también Darma podría pasarte ese archivo, eso junto con el ejecutable .exe me soluciono el problema que tuve, en todo caso si intentaste todo eso no se como mas ayudar.

**Comment by crixymln** [comment]
Si, eso ya lo hice y no dio resultado. :S
