### ISSUE TITLE
Quest//errror 25230

### ISSUE THREAD

**Issue by Daniel-mecato** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#10]
https://es.wowhead.com/quest=25230/m%C3%A1s-que-una-enfermedad
![WoWScrnShot_091520_223951](https://user-images.githubusercontent.com/61131807/93289663-85d13900-f7a4-11ea-9711-c72e6b8ab7b6.jpg)
Sin seguimiento.

**Comment by athenaswow** [comment]
Corregido
