### ISSUE TITLE
Quest erro 25241

### ISSUE THREAD

**Issue by Daniel-mecato** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#11]
https://es.wowhead.com/quest=25241/la-tierra-corrupta
![WoWScrnShot_091520_224747](https://user-images.githubusercontent.com/61131807/93290064-81f1e680-f7a5-11ea-940f-0d7f833e8309.jpg)
No muestra en el mapa.

**Comment by athenaswow** [comment]
Corregido
