### ISSUE TITLE
misión bug la lección de la roca equilibrada 

### ISSUE THREAD

**Issue by darkhallow44** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#12]
en la misión hay que subirse en unos palos para matar a otros pandas, pero al subirse a los palos no deja atacar a los pandas
https://ibb.co/2YwS3cd
en este video muestra como debería de funcionar la misión
https://youtu.be/HYlw5U9sJ2k 
también al bajar de el palo el personaje queda dentro del palo y algunas veces al bajar del palo se buguea la cámara 
https://ibb.co/zFVW5fy
y tampoco deja saltar de un palo a otro, también hay algunos pandas en el suelo y deberían estar arriba de los palos 
también el palo que esta seleccionado en la siguiente imagen se mueve 
https://ibb.co/7r6GM4p
también en los lagos que están al rededor de esta zona el pj debería convertirse en diferentes animales como se muestra en este video, también en el video se puede ver bien como debería funcionar los palos del lago
https://youtu.be/BRL2-RfZ4Kc

**Comment by athenaswow** [comment]
Corregido
