### ISSUE TITLE
Bug Puerta Segundo Jefe Monasterio Shadopan HC

### ISSUE THREAD

**Issue by exanime159147** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#126]
Al momento de llegar al segundo Jefe en la mazmorra Monasterio Shadopan hc, al entrar se inicia un tipo de evento. El problema es cuando por ejemplo, un solo pj entra y sale de nuevo, cerrándose la puerta con los pjs por fuera sin volver a abrirse e impidiendo continuar con el resto de la mazmorra.

**Comment by exanime159147** [comment]
Dalsam
#afdr
Bug Monasterio Shadopan hc

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @exanime159147 
Necesitamos que al momento de reportar sea un poco mas especifico ya que todo lo que pueda aportar en el reporte nos es de gran ayuda. 
De igual manera verificaremos si este fallo aun sigue pasando dentro del reino oficial.
Muchas gracias.
