### ISSUE TITLE
Tótem capacitador.

### ISSUE THREAD

**Issue by Lalan5** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#129]
Pieck - Lalan#3779
https://es.wowhead.com/spell=192058/t%C3%B3tem-capacitador
Agrego el link de wowhead. No obstante, la habilidad sufrió un cambio para el parche 7.0.1
Adjunto descripción del tótem en juego.
https://imgur.com/CijpNPQ
El tótem no realiza la acción que debería, no aturde a todos los enemigos en un radio de 8m al finalizar los 5s.

**Comment by pangolp** [comment]
Hola, buenas noches. Gracias por el reporte. Vamos a cerrar el issue, debido a que ya se encuentra reportado por otra persona anteriormente. Le informamos que el hechizo, tiene una posible solución, la cual vamos a estar posiblemente probando en los próximos días. Saludos. https://github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria-/issues/97
