### ISSUE TITLE
el pala no regenera mana en combate 

### ISSUE THREAD

**Issue by darkhallow44** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#13]
https://ibb.co/WfrMPR7

**Comment by ARK-Warcraft** [comment]
Las clases meles inferiores a lv 10 no generan mana hasta que se escoja la especializacion, el pala esta bien, suba al lv 10 y te daras cuenta.

**Comment by pangolp** [comment]
@darkhallow44 gracias por el reporte, pero tienen que incluir un poco mas de cuerpo en lo posible, mas alla de que en el titulo, se entiende el tema del que se esta hablando, la idea es tener un poco mas de información al respecto. ¿Al final esto fue comprobado? ¿Funciona de la forma como menciona @ARK-Warcraft? Gracias a ambos por las respuestas y disculpen en la demora. Estoy revisando de atrás para adelante, todos los reportes.

**Comment by Aquiles-AthenasWoW** [comment]
Buena: 
este es un problema que ya se le dio solucion en la misma beta de pandaria. 
Muchas gracias.
