### ISSUE TITLE
Glifo de vuelo Zen No disponible

### ISSUE THREAD

**Issue by sectario** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#138]
Cuando uno aprende el Glifo de vuelo Zen del monje no aparece la habilidad para poder volar.
Este glifo permite que el monje se ponga a meditar y vuele. 
LINK de la habilidad: https://www.wowhead.com/spell=125883/zen-flight#changelog

PJ: Sectario
DC: Sectario#9142

**Comment by pangolp** [comment]
Hola, buenas noches, gracias por el reporte. Vamos a cerrar el mismo, debido a que se encuentra duplicado en el siguiente enlace: https://github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria-/issues/458. De todos modos le informamos, que ya contamos con un posible arreglo, el cual vamos a estar probando en los próximos días.
