### ISSUE TITLE
[Logro]-[La gloria del Héroe]- Consumption Junction

### ISSUE THREAD

**Issue by Nero-Is-Blazing** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#148]
**Pj** principal: Nero
**Discord**: Nero's#4598

_Descripcion_

En Drak tharon Keep el boss Trollgore debe ser vencido antes de que este aplique almenos 10 marcas, al matarlo nos dara el logro de Consumption Junction el cual es requisito para la gloria del heroe, lo he realizado ya de varias formas distintas y llevo ya 1 semana atascado intentando probando que no sea un bug.

**pruebas de como es:** https://www.youtube.com/watch?v=r6490OU8NiU

**Comment by HOLYSHET** [comment]
También tengo el mismo problema. A muchas personas les pasa lo mismo con ese logro, en mi caso es el único faltante para completar La gloria del héroe. Espero y solucionen esto rápido.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @Nero-Is-Blazing: 
Ya fue confirmado el error del jefe y esta pronto a ser reparado.
Si tiene algún otro reporte respecto a logros de mazmorras  por favor escríbame a mi discord personal Gmaquiles# 0058
Muchas gracias

**Comment by Aquiles-AthenasWoW** [comment]
Logro bug del metalogro La gloria del héroe # 131
