### ISSUE TITLE
[Logro] - [La gloria del Héroe] Jinete de dracos experto

### ISSUE THREAD

**Issue by Nero-Is-Blazing** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#149]
Pj principal: Nero
Discord: Nero's#4598

_Descripcion_

jinete de dracos experto requiere de matar los 3 dracos pero al realizar esto no me da el logro de jinete de dracos experto. 

_Pruebas_

![WoWScrnShot_050321_132204](https://user-images.githubusercontent.com/83606891/116916657-3e080080-ac13-11eb-89c5-2158b33f9908.jpg)

![WoWScrnShot_050321_132213](https://user-images.githubusercontent.com/83606891/116916659-3fd1c400-ac13-11eb-9f61-37cea4f992a5.jpg)

![WoWScrnShot_050321_132156](https://user-images.githubusercontent.com/83606891/116916652-3c3e3d00-ac13-11eb-849d-896ed337c228.jpg)

Como deberia ser: https://es.wowhead.com/achievement=1871/jinete-de-dracos-experto

**Comment by HOLYSHET** [comment]
Ese logro se puede realizar perfectamente, ayer dia 23 lo pude sacar. ( Tardas 3 días en sacarlo)

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: 
Solo 1 logro se encuentra bug para el logro general de la gloria del héroe 
Muchas gracias.
