### ISSUE TITLE
PJ BUG "Dalaran"

### ISSUE THREAD

**Issue by DanielD12345** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#152]
PJ principal: Nabor
Usuario de Discord: Daniel D#0238
Mi personaje esta bug en Dalaran y necesito que me teletransporte a otra zona para que me pueda cargar el juego.
Ya llego casi 1 mes asi y intente poner ticket con otro pj pero creo que no estan activados y nadie responde por los canales.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @DanielD12345 : su pjta fue llevado a su capital.
 De igual manera este no es el lugar para poner este tipo de reportes. 
Muchas gracias.

**Comment by DanielD12345** [comment]
Amigo te lo digo directo. Andate a la verga con tu sever de mierda que son
puros ladrones y los pj están rotos
