### ISSUE TITLE
Falta Npc de Quest [mazmorras de Ventormenta]

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#16]
https://es.wowhead.com/quest=27739/el-rey-de-los-gnolls

Nota: No se encuentra el npc de la mision.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @ARK-Warcraft : 
El npc ya fue agregado en la mazmorra. 
![image](https://user-images.githubusercontent.com/80021790/126505316-768e33a5-ce90-4c07-893b-372745d79a63.png)
