### ISSUE TITLE
Bug: Personaje Doblado

### ISSUE THREAD

**Issue by sammuel20** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#162]
Buenas tardes
Sammuel: Personaje Doblado
usuario de discord: Kamiloz#8958

Descripcion del problema: mi personaje sammuel se ve visualmente doblado y los demás jugadores también lo ven así, por favor me ayudan con este error

muchas gracias
![WoWScrnShot_051821_135359](https://user-images.githubusercontent.com/84410041/118708113-f374af80-b7e0-11eb-939a-89032ad95f96.jpg)

**Comment by CJMZ18** [comment]
ta melo dejalo asi

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @sammuel20: 
Estamos revisando la causa de ese tipo de interacción con los personajes. 
Pero si llegase a recordar lo que se encontraba haciendo al momento de que su personaje empezara con el problema puede escribirme a mi discord personal Gmaquiles# 0058
Muchas gracias
