### ISSUE TITLE
Mision: Purificación por fuego [las mazmorra]

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#17]
Mision id: https://es.wowhead.com/quest=27737/purificaci%C3%B3n-por-fuego

Boss id: https://es.wowhead.com/npc=46264/lord-quemado

objeto id: https://es.wowhead.com/item=62305/n%C3%BAcleo-%C3%ADgneo-de-lord-quemado

Nota: La mision se encuentra bug, cuando cogemos la mision y a la hora de realizarla el boss del id: 46264 no entrega el item de mision id: 62305, este objeto es totalmente individual para todos los miembros de la mazmorra que tengan la mision.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @ARK-Warcraft 
La mision ya se encuentra funcional 
![image](https://user-images.githubusercontent.com/80021790/126505768-d25744f1-f1c7-42ac-86e6-cc7f882c5550.png)
