### ISSUE TITLE
 [Minas de la Muerte]

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#19]
Nota: Esta mazmorra de lv bajo, esta fallando en todas sus dificultades, una ves que ingresas quedan en combate y al llegar 1 de los boses se bugea la mazmorra. Una ves que se reinicia la estancia y al entrar, ya no aparecen los adds de toda las mazmorra.

**Comment by ARK-Warcraft** [comment]
https://es.wowhead.com/the-deadmines

**Comment by athenaswow** [comment]
Reparado
