### ISSUE TITLE
Bug en la penúltima misión de los pandas "Nuevos Aliados"

### ISSUE THREAD

**Issue by Zorodragneel24** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#2]
Personaje: Xavier
Discord: zorodragneel#8693

La penúltima misión para que los pandas puedan salir de la isla llamada "Nuevos Aliados" debe de completarse con el NPC "Espíritu del maestro Shang Xi" en el Templo de los Cinco Albores, luego de su termino el mismo NPC te daría la misión de "Un nuevo destino" que es donde se llega a escoger la facción a la que se quiere pertenecer llevándote a Ventormenta u Orgrimmar dependiendo la elección.
Como podemos ver en la cadena de misiones en la pagina de Wowhead: https://es.wowhead.com/quest=29800/nuevos-aliados
Y también podemos ver en el video: https://www.youtube.com/watch?v=JYHKyDuW2i4&feature=youtu.be

En el servidor esta funcionando de la siguiente manera:  te dan la misión "Nuevos Aliados" donde se tiene que ir al Templo de los Cinco Albores para supuestamente entregar la misión pero al momento de hablar con el espíritu del maestro Shang nos da directo para escoger a que facción pertenecer y al escoger teletransportándome en mi caso a Ventormenta.
![WoWScrnShot_082320_234346](https://user-images.githubusercontent.com/70125568/91004733-a5f14c00-e59a-11ea-9266-9bffee0a6ac8.jpg)

**Comment by athenaswow** [comment]
Corregido
