### ISSUE TITLE
Mazmorra:  [Asedio del Templo de Niuzao] Facultad: Heroico / Normal y Desafió.

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#24]
Por favor arreglar completamente la mazmorra en Facultad normal y Heroico, Ya que en la beta de pandaría no sirve y la idea es pasar les las guías adecuadas donde pueden analizar claramente los encuentros tantos como Npc´s y Jefes de estancia.  

En este vídeo encontraran explicado detalles de cada habilidad de cada uno de los Jefes de Estancia:
https://www.youtube.com/watch?v=lMW87HyOw1o

En los siguientes vídeos encontraran un poco mas general del recorrido completo de la Mazmorra,para que observen cada detalle de Npc´s, Items y Habilidades de uso de Articulos. Para que haya un buen desarrollo de la Estancia.

https://www.youtube.com/watch?v=7xgtmN3cBw4
https://www.youtube.com/watch?v=6v4993IJ1p4
https://www.youtube.com/watch?v=QGau3uzmPSw

**Comment by athenaswow** [comment]
Reparado
