### ISSUE TITLE
Mazmorra:  [Cervecería del Trueno] Facultad: Heroico / Normal y Desafió.

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#25]
La mazmorra actualmente se puede realizar, pero se saltan mecánicas de jefes, también las misiones andan bug y por lo general debería funcionar al 100% para mas experiencia Blizz. En los siguientes vídeos son sacados de jugadores que en su época jugaban en el servidor de Blizzard Oficial.  

En la facultad normal les encuentro un buen vídeo para arreglar esa facultad como debe ser.
Video: https://www.youtube.com/watch?v=7owINtPdNqY

En la facultad Heroica tomaremos solo en cuenta los Jefes.
https://www.youtube.com/watch?v=Od46aGt4Cl8

Video de modo desafio: https://www.youtube.com/watch?v=iLiAqCJV2pg

**Comment by athenaswow** [comment]
Reparado
