### ISSUE TITLE
Mazmorra:  [Monasterio Escarlata] Facultad: Heroico

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#26]
En el servidor de Athenas encontramos unos errores muy comunes en cualquier servidor instantáneo, para empezar toca darles las mecánicas apropiadas a cada boss en esta dificultad Heroica, en el testeo de esta aplicare un video del oficial para que tengan en cuenta los Despojos y Habilidades de Jefes durante el encuentro, para recalcar en la beta en el ultimo boss No aparece o en si no funciona el npc la sacerdotisa  [Melenablanca], al salir de su escondite lucharemos normalmente el encuentro hasta cierto porcentaje de vida ella se envuelve en inmunidad y castea una habilidad llamada:  [Resurrección en masa] facultad de este boss que le permite revivir uno de los secuaces que matamos justo en el altar, una ves que revive al guerrero Durand, la inmunidad desaparece de la sacerdotisa y le comenzamos a dar hasta que muera al terminar el encuentro nos dara el logro y el loot.

Video para saber mas acerca del ultimo Jefe y los primeros de igualmente con sus respectivas mecánicas. 

https://www.youtube.com/watch?v=WR11jFdq0SI

**Comment by athenaswow** [comment]
Reparado
