### ISSUE TITLE
Mazmorra:  [Scholomance] Facultad: Heroico

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#27]
Esta estancia en Athenas Beta pandaría, se encuentra funcionando completamente mal, el primer Jefe: [Instructora Corazón Álgido]
no hace sus mecánicas como es debido, no entra a segunda fase tampoco, y pues unas ves derrotado las puertas no abren y totalmente no se puede continuar para ello se investigo y se selecciono un video donde podran tener encuenta todo sobre la estancia de Scholomance.

Video: https://www.youtube.com/watch?v=-XW3FLDrcTk

**Comment by athenaswow** [comment]
Reparado
