### ISSUE TITLE
los poderes no se reinician al dar duelo y ceder 

### ISSUE THREAD

**Issue by darkhallow44** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#28]

**Comment by Juan-9904** [comment]
Las habilidades reinician su tiempo de reutilización si uno se desconecta mientras estas en Cooldown.
Ejemplo: Después de un duelo los Cooldown que estén en enfriamiento se siguen recargando, pero si nos desconectamos, estos  serán reiniciados por completo y tendrán que volver a cargarse desde 0 ya que parecería como si los hubiéramos acabado de usar.
------------------------------//------------------------------
The abilities restart their Reloading time if we log-out meanwhile they are reloading . Just like the ability was used recently.

**Comment by ARK-Warcraft** [comment]
De hecho creo que es normal que pase eso, si ya usaste las habilidades toca esperar a que se recarguen, lo que hicieron en el cata fue cambiar el metodo cuando termina un duelo se reinician por completo todas las habilidades por ello consigue traer consecuencias como saturar el servidor invocando varias objetos a traves del reinicio o simplemente se le llama desorden. pero esta bien lo que ahorita esta ya que eso impide los errores que pasa en cata por estar reiniciando los hechizos que estan en tiempo de cooldown.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
Esa es una condición que ponemos nosotros en experiencia de juego. 
La forma normal/correcta seria que no se reiniciaran al terminar un duelo.
Pero se pone así para que la gente no tenga que esperar varios minutos a sus cds.
