### ISSUE TITLE
Abilities problem

### ISSUE THREAD

**Issue by Juan-9904** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#29]
Se ha evidenciado que las habilidades que dejan un buff de tiempo en el personaje desaparecen luego de pasados unos 7 o 10 segundos desde que empezo la cuenta atras. 
Ejemplo: Al usar Colera Vengativa del paladin, normalmente duraria 20 seg, pero pasados 10 seg desaparecen automaticamente.
Esto pasa con cada uno de los Cd's globales del paladin y por lo que tengo entendido con otras clases tambien.
-------------------//---------------------------------------
It has been noticed the Skills that leave a time buff on the character dissapear after about 7-10 seconds after the countdown started.
Example: When  we use the Paladin's Wings, it would normally let on us a buff of 20 seconds with increase damage, but after 10 seconds they automatically disappear.
This happens with every single Global  of the Paladin and from what I understand after talk with other people that use other classes this happen to  other classes as well.

**Comment by Nefertumm** [comment]
Fixed
