### ISSUE TITLE
Tiempos de beneficios y casteos a la mitad

### ISSUE THREAD

**Issue by Zorodragneel24** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#3]
Personaje: Xavier, Xavierholy
Discord: zorodragneel#8693

Los beneficios ganado por poderes o pasivas, como podrían ser: "Palabra de poder: escudo" y "Ataque de la victoria" en sacerdote y guerrero respectivamente debería cumplir un tiempo determinado como se establece en los links: https://es.wowhead.com/spell=17/palabra-de-poder-escudo
https://es.wowhead.com/spell=122979/ataque-de-la-victoria

Los tiempos de casteo y beneficios ganados por poderes y pasivas están reducidos a la mitad, en el caso de "Palabra de poder: escudo" el tiempo que debería ser de 15s termina siendo de 7.5s, tal poder también deja un debuff llamado "Alma debilitada" que impide volver a colocar el escudo hasta que termine el tiempo del debuff lo cual también esta reducido a la mitad. Tal como se puede apreciar en el Gif:
![World-of-Warcraft-2020-08-25-12-14-28_Trim](https://user-images.githubusercontent.com/70125568/91210490-e9e76c80-e6d2-11ea-8bbf-8a1339b5a436.gif)
(quise adjuntar tambien el gif del guerrero pero el archivo termino pesando 180mb y no me termina por descargar)

**Comment by Matatrox** [comment]
Éste error también sucede con las comidas.

**Comment by pangolp** [comment]
Hola @Zorodragneel24 y @Matatrox, buenas noches. Disculpen la tardanza en la respuesta. ¿Ese error todavia continua en el servidor actual? Porque fue un problema, que se reporto hace bastante tiempo y se había modificado. Como veo que la fecha es del 2020, posiblemente esto ya este arreglado hace tiempo. Si me pueden confirmar, gracias.

**Comment by Zorodragneel24** [comment]
Buenas tardes, si fue algo que se reportó durante la beta y ahora ya está solucionado.
________________________________
De: Walter Pagani ***@***.***>
Enviado: sábado, 26 de junio de 2021 17:55
Para: athenaswow/BugTracker-Athenas-WoW-Pandaria- ***@***.***>
Cc: Zorodragneel24 ***@***.***>; Mention ***@***.***>
Asunto: Re: [athenaswow/BugTracker-Athenas-WoW-Pandaria-] Tiempos de beneficios y casteos a la mitad (#3)


Hola @Zorodragneel24<https://github.com/Zorodragneel24> y @Matatrox<https://github.com/Matatrox>, buenas noches. Disculpen la tardanza en la respuesta. ¿Ese error todavia continua en el servidor actual? Porque fue un problema, que se reporto hace bastante tiempo y se había modificado. Como veo que la fecha es del 2020, posiblemente esto ya este arreglado hace tiempo. Si me pueden confirmar, gracias.

**Comment by pangolp** [comment]
Buenísimo, gracias por responder, trataremos de cerrar el tema entonces próximamente.
