### ISSUE TITLE
Las habilidades casteadas se usan al completar la mitad del casteo de esta//The casting abilities are casting with the half of the time caste complete

### ISSUE THREAD

**Issue by Juan-9904** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#30]
After complete the half of the cast for every single casting ability , including breathing under water, asphixia or just a Heal Ability like the Flah light of Paladin this instantly is used.
--------------------------//--------------------------------
Después de completar el casteo de cualquier Habilidad que sea casteable, incluyendo el respirar bajo el agua, asfixia o una habilidad de heleo como el Destello de Luz del Paladin, esta es usada instantáneamente.

**Comment by Nefertumm** [comment]
Fixed.
