### ISSUE TITLE
bug de macro

### ISSUE THREAD

**Issue by darkhallow44** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#31]
hace poco cree un macro con mi dudu feral el cual tenia que activar encarnación: rey de la selva id 102543, furia de tigre id 5217, rabia id 106952, vigilia de la naturaleza id 124974 y rugido salvaje id 52610.
macro: https://ibb.co/JtYbt7v
al usar el macro activa todo bien excepto rugido salvaje el cual no se activa con el macro intente cambiar el macro pero sigue sin funcionar, mire a ver si las habilidades tenían globalCooldown activándolas pero no tenían, cuando yo activo el macro y por aparte activo rugido salvaje si funciona.
al otro dia entre con mi pala y cree otro macro el cual le paso lo mismo 
macro: https://ibb.co/dKk6scW
este macro tenia que activar sentencia de ejecución id 114157, Guardian de los antiguos reyes id 86698, inquisición id 84963, vengador sagrado id 105809 y cólera vengativa id 31884 al activarlo todo funcionaba menos inquisición y pasaba lo mismo que con el dudu.
lo raro de esto es que inquisición y rugido salvaje que son los poderes que no funcionaron en el macro, son muy parecidos inquisición consume poder sagrado para aumentar el daño y rugido salvaje consume puntos de combo para aumentar el daño entonces estaba pensando que podía ser un error con los puntos de combo.
mas tarde con el dudu estaba cambiando los poderes de posiciones en el macro y logre hacer que rugido salvaje funcionara pero ya no funcionaba encarnación: rey de la selva.

**Comment by ARK-Warcraft** [comment]
Buenas Noches, El dia de hoy te sacare de la duda, el macro que hiciste no funciona por un solo detalle, cuando tu usas el macro que indicas en ese comentario hay un error. es que no puedes colocar 2 hechizos como Rugido Salvaje con Encarnación, Ambos comparte globalCooldown, si lo usas una ves el macro solo se le activara el primero de los hechizos que colocaste, antes de colocar mensajes fíjate bien individualmente cada hechizo, acabe de testear eso y lo único que puedo decirte si quieres que te funcione espicha 2 veces el macro para que se le pueda activar la encarnación después del rugido salvaje.

**Comment by Aquiles-AthenasWoW** [comment]
Muchos spells comparten cds con otros. 
Como bien dice @ARK-Warcraft  si pones dos spells con el mismo global cd estos no actuaran ambos al mismo tiempo, se tendra que esperar a que uno finalice para que el otro pueda ser utilizado.
