### ISSUE TITLE
Bug de reponerse picaro

### ISSUE THREAD

**Issue by Brystarr** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#33]
Cuando se esta en combate con el pícaro el reponerse no cura lo que es
La habilidad dice: Remate que consume los puntos de combo de cualquier objetivo cercano para restaurar el 5% de la salud máxima cada 3segundos 
Mi personaje tiene 391mil de vida y la habilidad me cura 7827 si
![Muestra](https://user-images.githubusercontent.com/67715306/95888171-5e8b6e80-0d46-11eb-8b3b-6b49c75205ea.png)
n tener ningún debuff, el reponerse me debería curar 19k de salud 
En la imagen sanación que se ve es la del reponerse hay 1 debuff pero no reduce sanación

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
Ese fallo ya fue corregido en la apertura del servidor. 
Muchas gracias
