### ISSUE TITLE
bug en misión por la luz de las estrellas 

### ISSUE THREAD

**Issue by darkhallow44** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#34]
https://es.wowhead.com/quest=27549/por-la-luz-de-las-estrellas
la misión se puede completar, pero no funciona como debería.
al iniciar la misión hay que ponerse unos anteojos que nos dan y al usarlos podremos ver unas luces que tenemos que recoger,
pero las luces las podemos ver sin usar los anteojos

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: 
Se le realizaran las pruebas actualmente para verificar que aun siga fallando la mision.
 Muchas gracias.
