### ISSUE TITLE
misión bug haz los honores

### ISSUE THREAD

**Issue by darkhallow44** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#35]
https://es.wowhead.com/quest=27669/haz-los-honores
en la misión tenemos que acercarnos a los mecanismos que hay en el centro de la sala y darle click derecho al objeto que nos dan,
después nos debería salir una cinemática y deberíamos aparecer en la parte de arriba y en ese lugar completarla.
el problema es que al ir al centro de la sala para usar el objeto, simplemente al acercarse se completa la misión, sin necesidad de usar el objeto, después al subir a la parte de arriba donde aparece que se tiene que completar la misión, no hay nadie, por lo tanto no se puede completar la misión.
así se debería completar la misión: 
https://youtu.be/ndTGkCLXJKc

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
Esta misión si presenta fallos. estamos tratando de encontrarle una solución pero de momento la reparación de misiones no es una prioridad dentro del servidor se deben dar prioridad a las reparaciones de crasheos, jefes y clases prioritaria mente. 
Muchas gracias.
