### ISSUE TITLE
Bug pj no puede resucitar

### ISSUE THREAD

**Issue by Fernan090125** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#352]
Mori en tolbarad al entrar el servidor hizo el reinicio y cuando voy a la zona donde se supone esta mi cadaver le doy en resucitar pero no sucede nada intente ir donde el angel pero este no realiza ninguna accion cuando le doy click, mi pj es "zaofi" es una pandaren chaman alianza

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @Fernan090125 : 
Revisaremos esa zona para verificar si le problema es general o solo de la zona. 
De igual manera si esto le vuelve a suceder, debe dejar un ticket ingame para que un gm pueda solucionarle el problema lo antes posible.
Cualquier otro problema puede contactarse directamente con migo vía discord. Gmaquiles# 0058 
Muchas gracias.
