### ISSUE TITLE
Duda con la reliquias de honor.

### ISSUE THREAD

**Issue by RogerCS1704** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#353]
Buenas noches. Tengo un problema con mi personaje monje viajero del viento y es que tengo 2 reliquias de honor que son unas espadas designadas como Hoja de Vapulear endurecida por la batalla. Y como se sabe el monje viajero del viento tiene como habilidades de armas la doble empuñadura que nos permite empuñar un arma de una mano en cada mano. El problema es que yo consegui estas 2 reliquias y los mejoré para asi pdoer levear a 85 pero al momento de equiparlas, solo me permite equipar una de estas, Y también soy testigo de que he visto a un PJ monje de la horda que estaba leveando, equipar unas reliquias pero de justicia, en este caso también serían espadas de una mano del mismo tipo, encima para levear con esas reliquias hasta 85. Quisiera saber cual es el prolema ya que no tendría sentido que sean de justicia o de honor.
**Aca tengo una equipada**
![image](https://user-images.githubusercontent.com/67833494/122632552-0d800700-d099-11eb-9b33-734796473779.png)

**y aca esta en mi inventario, como se puede ver son del mismo tipo**
![image](https://user-images.githubusercontent.com/67833494/122632571-3dc7a580-d099-11eb-841b-1cd2ff8cf64c.png)

**Y al momento de equiparla me sale este mensaje**
![image](https://user-images.githubusercontent.com/67833494/122632588-66e83600-d099-11eb-8176-a176f6d8f2bd.png)

Me gustaria colocar del PJ horda que me encontra para pdoer corroborar lo ya mencionado antes pero lastimosamenterecién me di cuenta de este medio
Mi PJ es Itherkael
Mi usuario de discord es ZackF.#8576
Este es el item sobre el cual estoy hablando y es una reliquia. 
https://es.wowhead.com/item=93848/hoja-de-vapulear-endurecida-por-la-batalla

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @RogerCS1704 
Ese item es único-equipado por lo tanto no puede tener dos iguales equipados. 
Muchas gracias.

**Comment by ghost** [comment]
Gracias por esa aclaración amigo, desconocía ese detalle.
