### ISSUE TITLE
Actualización Mazmorra: Templo del jade de dragón. Reporte 2021 

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#36]
Nombre pj: Elmacizo
Discordia: Javier-Kaelt#1194

[MoP Reporte Templo del Dragon de Jade Athenas.pdf](https://github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria-/files/5760958/MoP.Reporte.Templo.del.Dragon.de.Jade.Athenas.pdf)

Nota: En Todas las dificultades presentan el mismo error.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
De momento esa mazmorra se encuentra funcionando correctamente. no a su 100 % pero si se puede realizar sin problemas.
