### ISSUE TITLE
Zaela (PNJ) Tierras Altas Crepusculares.

### ISSUE THREAD

**Issue by Persefone4102** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#367]
Nivel: 35
Reacción: H
Facción: Clan Faucedraco
Tipo: Humanoide
Añadido en el parche 4.0.3.13277
Salud: 2,188

BUG: Se caen de las texturas evitando que se puedan coger/entregar misiones.

Pruebas: https://youtu.be/XwsajzSygD4

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
Actualmente el npc se encuentra en la posición correcta sin problemas para que se le entreguen misiones.
Muchas gracias por el reporte.
