### ISSUE TITLE
Año 2021, Misiones importantes a Arreglar antes de la Inauguración.  [El lanzador personal ultraseguro]

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#38]
Nombre pj: Elmacizo
Discordia: Javier-Kaelt#1194

La presente misión  [El lanzador personal ultraseguro] se encuentra fallando ya que esta al usar el Npc-Objeto: Lanzador Personal Ultraseguro ID: 41398 No Autocompleta la misión, y también este se encuentra en movimiento y por lo tanto deberían estar quietos sobre la plataforma el Npc: 41398 . 

Nota: Por otro lado también no funciona su dirección a donde lo debe arrojar, ya que este lo arroja a cualquier dirección del mapa y en ocaciones provocando la muerte del personaje. 

Mision: https://es.wowhead.com/quest=25839/el-lanzador-personal-ultraseguro 
Video de como debe funcionar: https://youtu.be/Vk60JTY6poo

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
La misión se puede completar pero no esta funcionando como debería.
