### ISSUE TITLE
Año 2021, Misiones importantes a Arreglar antes de la Inauguración.  [Ataque desde el cielo]

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#39]
Nombre pj: Elmacizo
Discordia: Javier-Kaelt#1194

La misión [Ataque desde el cielo] se encuentra fallando de tal forma que el objeto a usar:  [Bengala de señalización] Item-ID: 56048 No marca nada en la Zona y por lo tanto no completa los objetivos de la misión: [Ataque desde el cielo] ID: 25841.

Link Misión: https://es.wowhead.com/quest=25841/ataque-desde-el-cielo
Video Misión como debe Funcionar: https://youtu.be/pJhOrhQuvq8

**Comment by athenaswow** [comment]
Corregido
