### ISSUE TITLE
Año 2021,  [Inmersión en Vashj'ir], Misión:  [Marchar con el estómago lleno] 

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#40]
Nombre pj: Elmacizo
Discordia: Javier-Kaelt#1194

En la presente misión:  [Marchar con el estómago lleno] de la cadena de misiones de Vashj´ir no se puede realizar debido a que los Npc-ID: 40685 se encuentra de Clase Azul, lo que imposibilita al jugador matarlos para agarrar el item: 54845 con nombre de : Carne de cangrejo suculenta. El Npc no se puede atacar debido a que es un objetivo Azul.

Link Mision: https://es.wowhead.com/quest=25546/marchar-con-el-est%C3%B3mago-lleno

Item Mision: https://es.wowhead.com/item=54845/carne-de-cangrejo-suculenta

Npc Mision: https://es.wowhead.com/npc=40685/crust%C3%A1ceo-doblegarra

Link video como debe funcionar: https://www.youtube.com/watch?v=viWbfHtOXwQ

**Comment by athenaswow** [comment]
Corregido
