### ISSUE TITLE
Año 2021, [Inmersión en Vashj'ir], Zona y Npc´s de Nespirah.

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#42]
Nombre pj: Elmacizo
Discordia: Javier-Kaelt#1194

En esta zona se encuentra un pequeño problema con los Npc´s de las siguientes id´s y nombres:

ID: 41467  Nombre: Encantadora Idra´kess
ID: 41466  Nombre: Centinela Idra´kess

Estos dos Npc´s con Id´s: 41466 y 41467 se encuentran sus posturas Muertas, cuando en Realidad están vivos, al pasar por sus lados los podemos atacar pero el problema es que sus posturas no son correctas ya que estos se encuentran vivos y no muertos.

Zona: En la zona Nespirah se puede Usar Montura Terrestre pero al intentar usar una de estas para no estar caminando, sale el mensaje "No lo puedes usar mientras estas nadando", Haber si arreglan estos dos pequeños errores para tener una mejor movilidad en la zona y ver los npc´s vivos como deben estar.

**Comment by athenaswow** [comment]
Reparado
