### ISSUE TITLE
Año 2021,  [Descenso a Infralar],  [La Vorágine]

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#43]
Nombre pj: Elmacizo
Discordia: Javier-Kaelt#1194

El problema no es la misión por el momento ya que el portal hacia la Vorágine no se puede entrar y por lo tanto no se puede entregar la misión ya que el npc se encuentra en la Vorágine.

Link Misión: https://es.wowhead.com/quest=27203/la-vor%C3%A1gine

Npc que toca entregarle la Misión : https://es.wowhead.com/npc=45042/thrall

Portal de Vorágine: https://es.wowhead.com/object=249858/portal-de-vor%C3%A1gine

Vídeo de como se debe hacer la Misión: https://youtu.be/j6lCvTSdOe0

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: actualmente esta mision no funciona un 100 % como deberia pero si se puede realizar.
