### ISSUE TITLE
Año 2021, [Descenso a Infralar], [Diario del Capitán]

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#44]
Nombre pj: Elmacizo
Discordia: Javier-Kaelt#1194

El objeto no entrega la misión ID: 26246.

Objeto: https://es.wowhead.com/object=204274/diario-del-capit%C3%A1n

Misión: https://es.wowhead.com/quest=26246/el-diario-del-capit%C3%A1n

Vídeo de como se hace la Misión: https://youtu.be/OOB9CKV81Ns

**Comment by athenaswow** [comment]
Corregido
