### ISSUE TITLE
Año 2021,  [Desenterrando Uldum], Misión: [Dinero fácil] 

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#45]
Nombre pj: Elmacizo
Discordia: Javier-Kaelt#1194

Debería salir una Cinemática cuando se acompaña a la Caravana y luego de acabarse dicha Cinemática el personaje debe aparecer en la Ciudad perdida de los Tol´vir.

Link Misión: https://es.wowhead.com/quest=27003/dinero-f%C3%A1cil

Vídeo de como debería funcionar: https://youtu.be/AoUt7YcuebQ

**Comment by Aquiles-AthenasWoW** [comment]
Buenas
Actualmente esta quest no hace la cinemática pero si se puede completar.
