### ISSUE TITLE
Bug: Glifo de Vuelo zen (Monje)

### ISSUE THREAD

**Issue by Persefone4102** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#458]
Hola, buen día, quisiera reportar un fallo en el glifo de vuelo zen: Al momento de aprenderlo y luego colocarlo en nuestra lista de Glifos, debería aprenderse automáticamente la habilidad "Vuelo zen", pero no pasa nada, el hechizo no se encuentra en el libro de hechizos generales ni en el de hechizos por especialización (en mi caso, Viajero del Viento), adjunto debajo las evidencias.

Nombre del PJ Principal: Distorted
Discord: Robs ♏#9926
Spell en Wowhead: https://es.wowhead.com/spell=125883/vuelo-zen

Video - Funcionamiento normal del Glifo: https://youtu.be/htiqzV96em0
Video - Evidencia del Fallo en Athenas: https://youtu.be/jky_PljBiDo

Ahi disculpen la calidad del video, no tengo un buen PC.
Gracias a los MJs por su colaboración in-game el día de hoy.

![27](https://user-images.githubusercontent.com/57680657/123881013-6d807400-d909-11eb-88fb-d3bd0a07db38.jpg)

**Comment by pangolp** [comment]
Hola buenas noches, en este momento estamos trabajando en un posible arreglo del problema. Agradecemos todos los reportes realizados y próximamente, estaremos informando cuando el mismo sea agregado al servidor oficial.

![WoWScrnShot_070621_002852](https://user-images.githubusercontent.com/2810187/124537992-4d612100-ddf1-11eb-9993-80f4fbcd607e.jpg)
