### ISSUE TITLE
Totem capacitador BUGG

### ISSUE THREAD

**Issue by Persefone4102** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#459]
Pj: Cutestorm
Crabbed # 4552

El tótem al invocarlo inicia una cuenta regresiva de 5seg, al llegar a 0 debe explotar y aturdir a todos los enemigos en un radio de 8metros, adjunto video donde se evidencia que no funciona.
https://youtu.be/np76nmiS2EA

https://es.wowhead.com/spell=192058/t%C3%B3tem-capacitador#changelog

**Comment by pangolp** [comment]
Hola buenas noches, el reporte ya fue realizado por otra persona.
https://github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria-/issues/97

Se cierra el tema, pero le informamos que ya tenemos un posible arreglo por probar.
Gracias por el reporte.
