### ISSUE TITLE
Año 2021, [Desenterrando Uldum], Misión: [Extirpadores ladrones]

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#48]
Nombre pj: Elmacizo
Discordia: Javier-Kaelt#1194

En esta Misión [Extirpadores ladrones], no esta funcionando el item que la misma misión otorga que es:  [Marra de la dinastía Tahret] con el ID: 63351, Al usar este item contra los npc no los derriba. 

Link Quest: https://es.wowhead.com/quest=28250/extirpadores-ladrones

Item de Quest: https://es.wowhead.com/item=63351/marra-de-la-dinast%C3%ADa-tahret

Video de como debe funcionar la Misión: https://youtu.be/pN0EZwAoZ5k

**Comment by athenaswow** [comment]
Corregido
