### ISSUE TITLE
Año 2021, [Desenterrando Uldum], Npc: Harrison Jones

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#49]
Nombre pj: Elmacizo
Discordia: Javier-Kaelt#1194

El Npc no se encuentra en su posición para hacer la entrega de la misión final:  [Haz los honores].

Npc ID: 48034

Link Npc: https://es.wowhead.com/npc=48034/harrison-jones

Video de la Misión como se hace y posición del npc que se le hace entrega de la misión: https://youtu.be/TcUVa9ZUJHE

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
Creemos que es algo simple de reparar pero verificaremos la complejidad de las fases para estar mas seguros.
