### ISSUE TITLE
bug de agro 

### ISSUE THREAD

**Issue by darkhallow44** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#5]
pj principal: panda
discord: darkhallow#6255
en pandaría hay unos monos llamados hozen fe-feng que deberían ser agresivos pero estos no atacan, solo atacan si uno los ataca 
https://ibb.co/bXMvmFK
en este video se puede ver como atacan los monos https://youtu.be/ZGfsI4eC7mg

**Comment by athenaswow** [comment]
Corregido
