### ISSUE TITLE
Año 2021, Recomendación de Aumentos de Experiencias. [Actual]

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#50]
Buen Día Comunidad de Athenas, de acuerdo a la experiencia dentro de la Beta y haber reportado algunos fallos, desde el punto de vista individual, las zonas se cuenta con un promedio de 55-60 misiones que completamente funcionan aunque considerando que tipo de experiencias debería tener el Reino. 

Cada misión cuenta con una cantidad de [x] Experiencia dependiendo del rango nivel que este y la gran mayoría de estas dan buenas bonificaciones. "Actualmente el Reino puede contar con la siguientes experiencias"

Bonificaciones Normales.
Experiencia x2
Honor x1
Profesiones x1
Reputación x1
Oro x1

Bonificaciones de Aumento [Fin de Mes] "x2 a lo anterior"

Experiencia x4
Honor x2
Profesiones x2
Reputación x2
Oro x2

Todo esto desde el punto comercio de Jugador a Jugador, ya que al tener tan elevados los aumentos de bonificaciones se perdería una gran parte de ventas en subastas, ya que omitirían cantidades pasos. Por Ejemplo: "tener profesiones aumentadas x4, arruinaría la comercialización de objetos ya que los puntos de experiencia suberian de 4 en 4 y al haber una bonificacion armadura de x2 estaría ganando 8 puntos adicionales."

Nota: Se tiene en cuenta desde el punto farmeo - comercio y logro.

**Comment by athenaswow** [comment]
Agregado
