### ISSUE TITLE
bug corte de casteo escudo indestructible (Qiang Camaras mogushan H)

### ISSUE THREAD

**Issue by sirsucio** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#502]
Opserc
Opserc#2171
chaman lvl 90

https://es.wowhead.com/spell=117961/escudo-indestructible?dd=5&ddsize=10

Encuentro con “Qiang el Despiadado” 

El bug es con el hechizo “Escudo indestructible” que al momento de castear dicho escudo se le puede cortar ese casteo (cosa que no debería poder realizarse).
Adjunto video del bug en el servidor https://www.youtube.com/watch?v=NjRPLl7tNLk&ab_channel=opserc

Adjunto video del funcionamiento del encuentro https://www.youtube.com/watch?v=6ZL6sh3sq7k&ab_channel=InnerSanctum (el encuento con este boss va desde el minuto 0:00 hasta el minuto 1:50)

**Comment by athenaswow** [comment]
Este bugg ha sido reparado
