### ISSUE TITLE
Bug en MoP

### ISSUE THREAD

**Issue by krauzerx** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#51]
usuario:Krauzerx
(La masmorra fue en corona del hielo, luego de que matamos al boss que tira púas 

Hice una masmorra con unos colegas, todo bien hasta que nos toco el último boss y se bugeo y a todos se nos trabo el pc y luego cuando reiniciamos la pc podía volar 
![Uploading 763D8C12-
![Uploading 8CE7D95A-13F7-458D-BD54-6FC1B608365F.jpeg…]()
4A0E-46B7-A564-B4FF7985395C.jpeg…]()

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
Este error ya no esta pasando actualmente dentro del servidor. 
Muchas gracias.
