### ISSUE TITLE
Bug  [La manera de la Horda] 

### ISSUE THREAD

**Issue by Creonnte** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#52]
PJ principal: Creonnte
Discord: Creonnte#8247

Buen dia.. 

Al momento de terminar la cadena de misiones de leveo de los pandas, me cuentro con el bug de que Garrosh, no sigue con la mision y no la puedo completar ya que el tiene que caminar por la sala para que si complete la mision.  

https://es.wowhead.com/quest=31013/la-manera-de-la-horda
https://www.youtube.com/watch?v=yV6zsFySiIQ&feature=emb_logo
Esta es la accion que se tiene que completar. 

Tambien al momento de levear en la zona de los pandas me tengo que salir del juego para que asi tome los cambios del mapa tales como seguir las misiones, ya que apenas acepto la mision no me sale en el mapa hasta que me salga y vuelva a entar, pasa mas queto en la entrega de misiones. 

(No se si eso ya ha sido arreglado y tampoco se si eso me pasa solo a mi)
Las misiones estan campletas, pero no se siente el cambio de ambiente, como la experiecia de la zona ya que la zona de los pandas tienen muchas cinematicas, y cambios ambientales o de esenario. 

Gracias..

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: 
Actualmente no recibimos ningun reporte similar. puede que sea una de las fallas del antiguo emulador utilizado. 
de igual manera revisaremos la zona y la cadena de misiones  para estar seguros.
Muchas gracias.
