### ISSUE TITLE
Pagina de glifos deshabilitada 

### ISSUE THREAD

**Issue by Revenant086** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#529]
### Colocar en el reporte el nombre de su PJ principal.

Revenant

### Colocar en el reporte su usuario de discord (ej.: jugador#0123).

Angel Vera#2277

### Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.

-pagina de glifos

### Descripción del error comprensible para cualquier persona.

soy nivel 79 y no tengo habilitada la pagina de glifos están en gris  no puedo seleccionar nada

### Agregar fotos y/o vídeos.
![image](https://user-images.githubusercontent.com/37353658/128603164-a87795d4-fe6b-4038-a542-1e54b004c899.png)

-
-
-

**Comment by jairgtlll** [comment]
Amigo, para poder poner los glifos, primero debes comprarlos, luego de eso los debes equipar y ahi si te van aparecer en el apartado que esta en "gris"

**Comment by Aquiles-AthenasWoW** [comment]
Buenas.
Debe comprar los glifos a un inscriptor o en subasta. 
Tambien puede crear sus propios glifos poniendose su profesion como inscripcion.
