### ISSUE TITLE
No hay mucho que recoger en Cataclysm

### ISSUE THREAD

**Issue by nefarian2012** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#53]
Pj principal: Rukiya
Discord: Rukiya#7857

Buenos dias .

Estos dias he estado tratando de farmear en varios sitios para recolectar recursos para herbolisteria, uso el addon Carbonite, para guiarme mejor en saber donde poder buscarlos mejor, tengo el conocimiento de que no muestra donde estan exactamente pero deja una guia de donde podrian estar... el problema esta en que no hay mucho que recoger, estuve dandole varias horas a los mapas Uldum, Infralar y Tierras Altas crepusculares y no se ve mucho de nada... inclusive descarte la idea de que estuvieran otros pjs por el area recolectando por las horas en que me conectaba a farmear (madrugada) 

Items:

https://es.wowhead.com/object=202750/flor-de-corazón
https://es.wowhead.com/object=202752/colátigo
https://es.wowhead.com/object=202747/flor-de-ceniza
https://es.wowhead.com/object=202751/jazmín-crepuscular

Si pueden darse cuenta, en las imagenes del wowhead se ven varios puntos de posible recoleccion, pero a la hora de ir a revisar no hay mucho que recoger... no se si sea un bug o fallo o lo dejan asi para que sea mas dificil, pero por una amable sugerencia diria que es mejor que dejen un indice de recogida mas alto.

Muchas gracias por su atencion.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
revisaremos la posibilidad de aplicar mas plantas dentro del juego
Muchas gracias.
