### ISSUE TITLE
Bug mop 

### ISSUE THREAD

**Issue by krauzerx** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#54]
29/1/2020
                    Bug del poder del monje 
Usuario: KungLaoo
Buenas tardes, La patada del dragón volador es un poder el cual uno salta hacia adelante para utilizar la patada del dragón volador para aterrizar e infringir daño a todos los enemigos en un radio de 8 metros y lo realentiza 8 segundos, cuando utilizó esta habilidad del monje no me ovaciona daño ni realentiza al objetivo.

https://user-images.githubusercontent.com/77549455/106323385-5ac41f00-6245-11eb-8605-e478417209a4.MOV

**Comment by athenaswow** [comment]
La patada ahora funciona perfectamente
