### ISSUE TITLE
Año 2021, Mision: Trampas para cangrejos de Tua'kea

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#55]
Nombre pj: Atlantiss
Discordia: Javier-Kaelt#1194

En esta Misión solo se requiere implementar mas de 15 trampas en la Zona ya que si visualizan en wowhead muestra cada uno de los puntos exactos de cada trampa pero en el servidor solo se cuenta con 4 trampas y su Respawn es Bajo lo que hace la misión muy larga a pesar de su facultad que debe ser muy fácil. 

Mision: https://es.wowhead.com/quest=12009/trampas-para-cangrejos-de-tuakea#videos-english

Objeto de Misión: https://es.wowhead.com/item=35802/trampa-para-cangrejos-de-tuakea

Vídeo de Misión como se debe hacer: https://youtu.be/xK1ZgRje9Ro

**Comment by athenaswow** [comment]
Corregido
