### ISSUE TITLE
Año 2021, Misión: ¿Qué fue primero? ¿El draco o el huevo?

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#56]
Nombre pj: Atlantiss
Discordia: Javier-Kaelt#1194

La misión no se puede realizar debido a que los huevos de la zona no funcionan ya que deberían salir unas Crías Abisales al espichar sobre el Huevo empieza a castear, al finalizar el casteo debe salir la cría abisal id: 20021 para luego utilizar el objeto de la misión y completar alguna de las 3 esencias, actualmente solo esta fallando los huevos presentes de la zona ya que cuando termina el casteo no sale el Npc 20021 y vuelve a reaparecer infinitamente el Huevo, igualmente si no entienden lo que explique lo invito ver el vídeo al final de esta publicación como se debería realizar la misión.

Unas de la alternativas que yo veo es reemplazar todos los Huevos de la Zona por el Npc: 20021 Cría Abisal para poder realizarla normalmente el día de la Inauguración de pandaría. 

Misión: https://es.wowhead.com/quest=10609/qu%C3%A9-fue-primero-el-draco-o-el-huevo#videos-english

Npc: https://es.wowhead.com/npc=20021/cr%C3%ADa-abisal

Vídeo de como se debe hacer la misión: https://youtu.be/HWgtCF5pKqc

**Comment by athenaswow** [comment]
Corregido
