### ISSUE TITLE
Año 2021, Misión: Noticias frescas: ¡el fuego sigue estando caliente!

### ISSUE THREAD

**Issue by ARK-Warcraft** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#57]
Nombre pj: Atlantiss
Discordia: Javier-Kaelt#1194

La misión esta fallando, a primera vista no podría decir que es en realidad lo que estaría fallando si es el ítem o npc, solo se que cuando uno empieza a realizar la misión esta te otorga un objeto: 41131 Extintor Garrafuria, este sirve para apagar el fuego de las cabañas de la zona que muestra en el foro de Wowhead, cada fuego es un Npc identificado con id: 29692 supongo que al utilizar el objeto 41131 este lanzara un Hechizo al objetivo 29692 y automáticamente lo apagaría o mataría, completando 1 punto de la misión. Actualmente se lanza el hechizo y apaga el fuego pero no otorga puntos de la misión. Al final de este post esta los enlaces de cada objeto, npc, quest y vídeo para que logren entender un poco y poder arreglar la misión. 

Misión: https://es.wowhead.com/quest=12859/noticias-frescas-el-fuego-sigue-estando-caliente#videos-english

Item Extintor Garrafuria: https://es.wowhead.com/item=41131/extintor-garrafuria

Npc Fuego Cabaña: https://es.wowhead.com/npc=29692/fuego-caba%C3%B1a

Vídeo de como se debe hacer la misión: https://youtu.be/Hem5kVwi-8o

**Comment by athenaswow** [comment]
Corregido
