### ISSUE TITLE
Animaciones Brujo

### ISSUE THREAD

**Issue by reex1288** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#58]
Pj principal : Verminus
Usuario de discord : reex1288#6663

Las animaciones de las barras de recursos ( burning embers, soul shard y demonic fury ) de las 3 specs de brujo no poseen su animación visual en el servidor de pandaria.
Burning embers : no hay animacion
Soul shards : No hay animación
Demonic Fury : No hay animación

Imagenes o videos representativos

https://www.youtube.com/watch?v=DjyK1AfJnoI ( Burning embers ) 

![image](https://user-images.githubusercontent.com/75642871/113490283-4b9c6000-9486-11eb-991d-27d07553e5f0.png)  

( soul shards de aflicción / glifo de verdant spheres.

https://www.youtube.com/watch?v=LlAyOFSDORE
Minuto 3:30. el warlock demonologia es rodeado de energia al llegar altas cantidades de furia demoniaca sin usar.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @reex1288 :
Necesitaríamos un vídeo explicando a detalle el problema. 
Muchas gracias.
