### ISSUE TITLE
Misión de monje lvl 20 NPC aparece de nivel muy alto. Clase_Monje

### ISSUE THREAD

**Issue by destraud** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#60]
Pj Zangetsu
Discord Destru#0951

La misión "Comienza tu entrenamiento: Maestro Cheng" tiene el bug que el npc Maestro cheng que es el con quien peleas, antes de hablar con el es nivel 20 pero después de hablar sale un faseo y se convierte en uno de nivel aleatorio. He llegado a ver que sale hasta lvl 78, 53, 64 o 25 que fue cuando pude derrotarlo. Su verdadero nivel debe ser 20 con 1572 puntos de vida.

Tambien falta que use su habildiad de quemar que es la más importante.

anexo 1 video del oficial: https://es.wowhead.com/quest=31834/comienza-tu-entrenamiento-maestro-cheng#videos:id=173880
Anexo 2 video del athenas mop: https://youtu.be/r4ygiVtmd58

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: 
Actualmente esto ya no esta pasando dentro del servidor. 
Muchas gracias
