### ISSUE TITLE
Bug en misión nivel 83 - Uldum - Guardianes colosales

### ISSUE THREAD

**Issue by MANUELPROGRA** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#62]
https://es.wowhead.com/quest=27623/guardianes-colosales
 EL problema de esta misión no se puede matar al coloso del sol porque esta bajo tierra, es necesario para poder obtener 

  | Piedra del Sol

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @MANUELPROGRA 
Esta misión si se puede realizar actualmente dentro del servidor. 
Muchas gracias.
