### ISSUE TITLE
Es imposible sacar a las mujeres goblin de kezan

### ISSUE THREAD

**Issue by jeiduart** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#63]
Nombre del pj: Tainys
Discord: Tainys#8409

Bueno como dice el titulo es imposible sacar a las mujeres de la raza goblin ya que en cierto punto no te dan misiones.

Primero que nada si te colocas a leer las misiones de de los goblin en la isla tienes un novio(a) y un amigo(a), si eres hombre tu novia es https://es.wowhead.com/npc=35053/cara-melo y tu amigo es https://es.wowhead.com/npc=35054/locko-mia y si eres mujer tu novio es https://es.wowhead.com/npc=35054/locko-mia y tu amiga es https://es.wowhead.com/npc=35053/cara-melo, dicho esto cuando llegas a la mision https://es.wowhead.com/quest=26712/al-banco si eres hombre te la da cara melo y si eres mujer la mision te la da locko mia, resulta que al goblin hombre los 2 npc le dan la mision :
![1](https://user-images.githubusercontent.com/60366740/113539380-b4c9c380-95ab-11eb-9a5a-c5b7945d52c3.png)
![2](https://user-images.githubusercontent.com/60366740/113539419-c6ab6680-95ab-11eb-8e7f-6302d6f11277.png)
![3](https://user-images.githubusercontent.com/60366740/113539448-d6c34600-95ab-11eb-8179-cb0e4fbdd997.png) 

Bueno un GM me ayudo con las da el npc locko mia el cual da 2 misiones que nunca me dio https://es.wowhead.com/quest=26711/al-banco,   https://es.wowhead.com/quest=14153/el-alma-de-la-fiesta, las 2 misiones me las tubo que dar el GM, con esto pude salir de la isla de kezan, bueno ahora llegue a las islas perdidas y me encontre con el mismo bug, en islas perdidas la primera mision la pude hacer https://es.wowhead.com/quest=14239/no-vayas-hacia-la-luz pero la siguiente mision que es diferente dependiendo del tu sexo https://es.wowhead.com/quest=14001/c%C3%A1psulas-de-escape-goblin,  https://es.wowhead.com/quest=14474/c%C3%A1psulas-de-escape-goblin, no me la dio e intente con otro goblin compartirmela y me salia que no cumplia con los requisitos aunque con ambos pj habia hecho las mismas misiones, ademas que al goblin hombre le daban 2 veces la mision.
![4](https://user-images.githubusercontent.com/60366740/113540774-d8dad400-95ae-11eb-92d6-8fb956665ff0.png)

Acá se puede ver que al goblin hombre le dan 2 veces la misión.
![5](https://user-images.githubusercontent.com/60366740/113540819-f1e38500-95ae-11eb-8e46-f058368d063f.png)

Bueno un gm me ayudo con la mision y asi pude seguir adelante hasta que llegue a las ultimas misiones en donde como era de esperarse no me daban las misiones de matar a los npc de los que hable al inicio, arrancar el corazón de Locko Mia https://es.wowhead.com/quest=25202/el-camino-m%C3%A1s-r%C3%A1pido-al-coraz%C3%B3n#screenshots y matar a Cara Melo https://es.wowhead.com/quest=25244/qu%C3%A9-clase-de-nombre-es-cara-melo ya despues de estas misiones faltarian completar de 2 a 3 misiones mas y salimos de la isla, pero hay me quede ya que ningun npc me da las misiones y por si se lo preguntan si hice toda la cadena de misiones sin saltarme ni una, incluso  haciéndolas con el cazador doblecuentiando pero nada. Sinceramente no entiendo por que sera el bug.

Por favor si pueden arreglarlo rápido seria genial.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @jeiduart: 
Este fallo ya fue solucionado dentro del servidor. 
Muchas gracias  por su reporte nos fue de mucha ayuda para poder solucionarlo.
