### ISSUE TITLE
Totem incapacitator del shamán está bugueado

### ISSUE THREAD

**Issue by Joao19-hash** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#65]
cual es el problema?: El totem no está estuneando ni haciendo la animación correspondida

Comentario adicional: El bug es bastante grave

**Comment by pangolp** [comment]
@Joao19-hash Buenas noches. El reporte, necesita mejorar bastante. Por favor, la próxima vez que realice un reporte, no deje de subir enlaces de wowhead, o de algún otro sitio para tener mas información del problema. También es recomendable, subir un video, que demuestre el fallo del mismo. De todos modos le informo, que el error va a ser próximamente reparado. Espero por favor, que la próxima el reporte, cuente con la información necesaria.

Otros reportes relacionados:
https://github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria-/issues/129
https://github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria-/issues/459

Un ejemplo de un buen reporte, es el siguiente:
https://github.com/athenaswow/BugTracker-Athenas-WoW-Pandaria-/issues/97
