### ISSUE TITLE
Misiónes - Pandaria:  Instrucción de vuelo nimbo

### ISSUE THREAD

**Issue by MANUELPROGRA** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#66]
Las misiones:
https://es.wowhead.com/quest=30144/instrucci%C3%B3n-de-vuelo-pasar-por-el-aro
https://es.wowhead.com/quest=30145/instrucci%C3%B3n-de-vuelo-a-toda-velocidad
https://es.wowhead.com/quest=30187/instrucci%C3%B3n-de-vuelo-el-recorrido-correcto
no se pueden realizar .
misión importante en la cadenas misiones para obtener Habilidad Montar sobre dragones nimbo.

**Comment by MANUELPROGRA** [comment]
> Las misiones:
 https://es.wowhead.com/quest=30144/instrucci%C3%B3n-de-vuelo-pasar-por-el-aro
https://es.wowhead.com/quest=30145/instrucci%C3%B3n-de-vuelo-a-toda-velocidad
https://es.wowhead.com/quest=30187/instrucci%C3%B3n-de-vuelo-el-recorrido-correcto
 no se pueden realizar .
> misión importante en la cadenas misiones para obtener **Habilidad Montar sobre dragones nimbo**.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: 
Actualmente se esta trabajando en la reparación de estas misiones como alta prioridad.
