### ISSUE TITLE
[Misión] - [Los Baldíos del Norte] - ID: 881 - Echeyakee

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#68]
**PJ principal:** Jaeana
**Usuario de discord:** developer#5428

**Descripción del problema:**

Para completar la misión [Echeyakee](https://es.wowhead.com/quest=881/echeyakee#comments) requiere de ir a la Guarida de Echeyakee y usar el [Cuerno de Echeyakee](https://es.wowhead.com/item=10327/cuerno-de-echeyakee), pero, no se puede usar porque sale el aviso "Requiere Guarida de Echeyakee" siendo que ya estoy en el sitio correcto.

**Material multimedia de ayuda:**

Aquí un video de como debería funcionar: [ir al video](https://www.youtube.com/watch?v=boqkHhehkf0).

**Comment by Aquiles-AthenasWoW** [comment]
Buenas :
esa misión es engañosa. ya que la posición que sale en wowhead no es la misma de donde debería estar en pandaría.
aqui le dejo una imagen donde realmente sale el npc.
![image](https://user-images.githubusercontent.com/80021790/126526244-f1f50849-c1ab-4f02-b4e3-74a90f1420d6.png)
