### ISSUE TITLE
[Misión] - [Los Baldíos del Norte] - ID: 13975 - Entrega de caravana de El Cruce

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#69]
**PJ principal:** Jaeana
**Usuario de discord:** developer#5428

**Descripción del problema:**

Para completar la misión [Entrega de caravana de El Cruce](https://es.wowhead.com/quest=13975/entrega-de-caravana-de-el-cruce) requiere de hablar con el NPC [Rocco Azotaespinillas](https://es.wowhead.com/npc=34578/rocco-azotaespinillas), este NPC nos proveerá el objeto [Barrecaminos de Halga](https://es.wowhead.com/item=46714/barrecaminos-de-halga) y también de un [Kodo de caravana principal](https://es.wowhead.com/npc=34577/kodo-de-caravana-principal), debemos montarnos en el
[Kodo de caravana principal](https://es.wowhead.com/npc=34577/kodo-de-caravana-principal) y usar el arma [Barrecaminos de Halga](https://es.wowhead.com/item=46714/barrecaminos-de-halga) contra las oleadas de NPC's hasta llegar al sitio "El cruce". El problema es que el NPC [Rocco Azotaespinillas](https://es.wowhead.com/npc=34578/rocco-azotaespinillas) no muestra el diálogo donde nos proveerá de los objetos [Barrecaminos de Halga](https://es.wowhead.com/item=46714/barrecaminos-de-halga) y [Kodo de caravana principal](https://es.wowhead.com/npc=34577/kodo-de-caravana-principal).

**Material multimedia de ayuda:**

Aquí un video de como debería funcionar: [ir al video](https://www.youtube.com/watch?v=x806X_oCs68).

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: 
Esta mision si esta fallando pero no es prioridad en este momento. 
de igual manera se repararan apenas demos por concluido problemas con crasheos y spells de jefes y clases.
Muchas gracias.
