### ISSUE TITLE
Misión "Torek's Asualt" Bug.

### ISSUE THREAD

**Issue by Matatrox** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#7]
Personaje: Zyvo
ID Discord: Anthony#0581
Pedís la misión, das 2 pasos y te la da como completada.
Vídeo de como debería ser la misión: https://www.youtube.com/watch?v=RYpuzb5uYx0

**Comment by pangolp** [comment]
Hola @Matatrox, ¿continua bug la misión? Gracias por la respuesta y disculpa la demora.

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: 
Esta mision ya se encuentra funcionando dentro del servidor.
Muchas gracias.
