### ISSUE TITLE
[Misión] - [Los Baldíos del Norte] - ID: 29109 - La recogida de la caravana de Mor'shan

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#70]
**PJ principal:** Jaeana
**Usuario de discord:** developer#5428

**Descripción del problema:**

Para completar la misión [La recogida de la caravana de Mor'shan](https://es.wowhead.com/quest=29109/la-recogida-de-la-caravana-de-morshan) requiere de hablar con el NPC [Rocco Azotaespinillas](https://es.wowhead.com/npc=52220/rocco-azotaespinillas), este NPC nos proveerá de un [Kodo jefe de caravana](https://es.wowhead.com/npc=52209/kodo-jefe-de-caravana), debemos montarnos en el [Kodo jefe de caravana](https://es.wowhead.com/npc=52209/kodo-jefe-de-caravana) y llegar al campamento calígine. El problema es que el NPC [Rocco Azotaespinillas](https://es.wowhead.com/npc=52220/rocco-azotaespinillas) no está en el lugar.

**Material multimedia de ayuda:**

Aquí un video de como debería funcionar: [ir al video](https://www.youtube.com/watch?v=WBIrmfnFTpU).

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: Todas las misiones relacionadas con caravanas no están funcionando dentro del juego.
Como dije con anterioridad se les dará prioridad de reparación una vez que terminemos con los crasheos y fallos de spells en jefes y jugadores.
Muchas gracias.
