### ISSUE TITLE
[Misión] - [Los Baldíos del Norte] - ID: 14006 - Lee el manual

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#71]
**PJ principal:** Jaeana
**Usuario de discord:** developer#5428

**Descripción del problema:**

Para coger la misión [Lee el manual](https://es.wowhead.com/quest=14006/lee-el-manual) requiere de hablar con el NPC [Petardol](https://es.wowhead.com/npc=3442/petardol), el problema es que el NPC no entrega la misión.

**Material multimedia de ayuda:**

Aquí un video de como debería funcionar: [ir al video](https://www.youtube.com/watch?v=2hu_Y4CZo5w).

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
Esta mision si esta funcionando dentro del servidor. ya que la mision cuenta con ir a "armar" el manual matando los goblins y a su jefe en la parte noroeste del mapa.
Luego de esto si nos dejara leer el manual.
Muchas gracias.
