### ISSUE TITLE
[Misión] - [Los Baldíos del Norte] - ID: 14072 - Alertar a Verog

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#72]
**PJ principal:** Jaeana
**Usuario de discord:** developer#5428

**Descripción del problema:**

Para coger la misión [Alertar a Verog](https://es.wowhead.com/quest=14072/alertar-a-verog) requiere de hablar con el NPC [Herradura](https://es.wowhead.com/npc=34638/herradura). El problema es que el NPC no entrega la misión.

**Material multimedia de ayuda:**

Aquí un video de como debería funcionar: [ir al video](https://www.youtube.com/watch?v=t5riaVp0fxY).

**Comment by Aquiles-AthenasWoW** [comment]
Buenas:
Esta mision si se puede realizar dentro del servidor.
