### ISSUE TITLE
[Misión] - [Los Baldíos del Norte] - ID: 870 - Las Charcas del Olvido

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#73]
**PJ principal:** Jaeana
**Usuario de discord:** developer#5428

**Descripción del problema:**

Para coger la misión [Las Charcas del Olvido](https://es.wowhead.com/quest=870/las-charcas-del-olvido) requiere de hablar con el NPC [Tonga Tótem de Runa](https://es.wowhead.com/npc=3448/tonga-t%C3%B3tem-de-runa). El problema es que el NPC no entrega la misión.

**Material multimedia de ayuda:**

Aquí un video de como debería funcionar: [ir al video](https://www.youtube.com/watch?v=O96u9lDseQI).

**Comment by Aquiles-AthenasWoW** [comment]
buenas:
Esta misión si se puede realizar dentro del servidor.
