### ISSUE TITLE
Quest error//Aerofobia

### ISSUE THREAD

**Issue by Daniel-mecato** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#8]
Como de funcionar https://www.youtube.com/watch?v=zteGNryJI7Q&feature=youtu.be
Como está
![WoWScrnShot_091520_010110](https://user-images.githubusercontent.com/61131807/93171596-03d30880-f6ef-11ea-9c8b-3b891e23166c.jpg)
Además no salir en mapa el seguimiento.

**Comment by athenaswow** [comment]
Corregido
