### ISSUE TITLE
Doble especialización pícaro cuesta demasiado.

### ISSUE THREAD

**Issue by Hanae987** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#80]
Resulta que estaba en el instructor de pícaros de ventormenta (casco antiguo), y cuando iba me decía que no tenía suficiente dinero y yo con 500 de oro, después de un tiempo llegue a 1100 de oro y fuí a comprar la doble especialización(ya habían pasado 2 o 3 días) y me cobro 1000 de oro, no me mostro cuanto iba a costar ni si estaba seguro de comprarla y me di cuenta que me costo 1000 de oro porque abrí mi inventario para ver si tenía plantas y vi que me faltaban 1000 de oro.

**Comment by athenaswow** [comment]
Reparado
