### ISSUE TITLE
URGENTE Bug SELECCIÓN DE OBJETIVOS EN PANDARIA

### ISSUE THREAD

**Issue by JnicolasM** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#81]
Servidor pandaria
Pj: Doltas
Discord: nicolas#9380

Link YouTube: https://www.youtube.com/watch?v=B7Su_bigjps 

El problema es el siguiente, al cambiar de objetivo para lanzar una habilidad, aun teniendo seleccionado el nuevo objetivo, el pj ataca al objetivo anterior, en el video se evidencia claro, es importante corregirlo ya que esto puede afectar gravemente el cc en arenas

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @JnicolasM :
Este problema fue revisado y no esta pasando dentro del servidor. 
Si esto llegase a volver a pasar puede comunicarse con migo a mi discord personal:
Gmaquiles# 0058 
Muchas gracias.
