### ISSUE TITLE
[Misión] - [Isla Luna Negra] - ID: 29455 - Objetivo: tortuga

### ISSUE THREAD

**Issue by ghost** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#85]
**PJ principal:** Jaeana
**Usuario de discord:** developer#5428

**Descripción del problema:**

Para completar la misión [Objetivo: tortuga](https://es.wowhead.com/quest=29455/objetivo-tortuga) se debe hablar con el NPC [Jessica Rogers](https://es.wowhead.com/npc=54485/jessica-rogers) y dando clic en uno de los diálogos este nos proveerá de unos anillos y nos habilitará una interfaz gráfica diferente para poder usar un hechizo para lanzar los anillos. El problema es que los diálogos no funcionan y no permite acceder a realizar el juego.

**Material multimedia de ayuda:**

Aquí un video de como debería funcionar: [ir al video](https://www.youtube.com/watch?v=RvlkPPKBUwk).

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: La feria de la luna negra esta deshabilitada completamente por fallos en la misma.
