### ISSUE TITLE
Quest error Silitidofobia

### ISSUE THREAD

**Issue by Daniel-mecato** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#9]
Como debe de funcionar https://www.youtube.com/watch?v=O3nGp7I4PWQ&feature=youtu.be
Como no funciona
![WoWScrnShot_091520_010435](https://user-images.githubusercontent.com/61131807/93171862-79d76f80-f6ef-11ea-8041-a5fd2240031f.jpg)

**Comment by Daniel-mecato** [comment]
Sin seguimiento en el mapa.

**Comment by athenaswow** [comment]
Corregido
