### ISSUE TITLE
Armas de Honor con precios equivocados

### ISSUE THREAD

**Issue by Infernose** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#93]
El nombre de mi PJ Principal es **Infernose**, Undead Mage Horda
Mi nombre de Discord **Uziell#1133**

El problema es el siguiente, algunas armas de honor, en el Vendor Lok'Nor Puño Sangre cuestan más de lo debido, algunas incluso más de 6.000 de honor, cosa que es imposible ya que el maximo permitido es de 4.000. Tampoco están a la venta las armas de Off-hand para casters, por lo que es imposible obtener armas para caster, ya que el bastón cuesta 6619 y no existen las Off-hand.

Los precios deberían ser los siguientes:

Bastones, Armas de dos manos, Armas de cazador **3.500** de honor
Dagas de _Caster_ y Varitas **2.250** de honor
Dagas de _Melee_ **1,750** de honor
Off-Hand de casters y escudos **1.250** de honor

Se dan cuenta que estos precios tienen más sentido si los suman y ven que cuesta igual para cada clase y spec comprar las armas.
![WoWScrnShot_041521_123335](https://user-images.githubusercontent.com/82601975/114919050-cbff8100-9df5-11eb-9142-0060dbb0f3a1.jpg)

**Comment by Aquiles-AthenasWoW** [comment]
Buenas: 
Esto ya fue solucionado dentro del servidor
Muchas gracias.
