### ISSUE TITLE
Habilidad Tótem Capacitador Bug (No stunea) (Chaman Mejora)

### ISSUE THREAD

**Issue by memoaparicio** [athenaswow/BugTracker-Athenas-WoW-Pandaria-#97]
Blaxters
Blaxterz#6266

Como debe funcionar:
Invoca un tótem a los pies del personaje (yo) absorbe energía eléctrica del aire que lo rodea y explota tras 5 s, lo que aturde a todos los enemigos en un radio de 8 m durante 5 sec.
https://www.youtube.com/watch?v=r_CbtShMTec (en el video se puede observar primero el error, luego puse lo que debería hacer el tótem)

Como funciona en el servidor Athenas Wow Mop:
El tótem solo esta quieto y desaparece (en el video se puede observar)

Link del hechizo en WowHead: 
https://es.wowhead.com/spell=192058/t%C3%B3tem-capacitador

**Comment by Aquiles-AthenasWoW** [comment]
Buenas @memoaparicio: 
Ya se esta trabajando en la solución del spell, se estan haciendo testeos para verificar que sea fixeado correctamente.
Cualquier duda o información que tenga relacionada a este o otros spells puede escribirme a mi Discord personal:
 Gmaquiles# 0058
Muchas gracias por su reporte.
